entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: nexusos_lipaira-net
  file:
    filename: /etc/traefik/lipaira-traefik-dynamic.yml

api:
  dashboard: true
  insecure: true

log:
  level: INFO
